services:
  - type: web
    name: telegram-music-bot-vc
    env: python
    buildCommand: "apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "python bot_vc.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PORT
        value: 8080
      - key: WEB_URL
        sync: false
